#!/usr/bin/env python3

# Standard library imports
from random import randint, choice as rc

# Remote library imports
from faker import Faker

# Local imports
from app import app
from models import db, User, Character,Deck,Card,Mob,MobDeck,Fight,InFightMobDeck,LevelChart

starter_deck = [
    {"card_name": "Magic Bolt"},
    {"card_name": "Magic Bolt"},
    {"card_name": "Magic Ward"},
    {"card_name": "Magic Ward"},
    {"card_name": "Magic Band-aid"},
    {"card_name": "Magic Band-aid"},
    {"card_name": "Vitality Transfusion"},
    {"card_name": "Wack Em"},
    {"card_name": "Wack Em"},
    {"card_name": "Wack Em"},
    {"card_name": "Hide Behind Somthing"},
    {"card_name": "Hide Behind Somthing"},
    {"card_name": "Hide Behind Somthing"},
]

if __name__ == '__main__':
    fake = Faker()
    with app.app_context():
        print("Dropping Undesirables...")
        User.query.delete()
        Character.query.delete()
        Deck.query.delete()
        Card.query.delete()
        Mob.query.delete()
        MobDeck.query.delete()
        Fight.query.delete()
        InFightMobDeck.query.delete()
        db.session.commit()
        print("Starting seed...")
        # Seed code goes here!
        print('Generating Level Chart...')
        levels_in_chart = [
            LevelChart(level='1', experience_cap='83'),
            LevelChart(level='2', experience_cap='174'),
            LevelChart(level='3', experience_cap='276'),
            LevelChart(level='4', experience_cap='388'),
            LevelChart(level='5', experience_cap='512'),
            LevelChart(level='6', experience_cap='650'),
            LevelChart(level='7', experience_cap='801'),
            LevelChart(level='8', experience_cap='969'),
            LevelChart(level='9', experience_cap='1154'),
            LevelChart(level='10', experience_cap='1358'),
            LevelChart(level='11', experience_cap='1584'),
            LevelChart(level='12', experience_cap='1833'),
            LevelChart(level='13', experience_cap='2107'),
            LevelChart(level='14', experience_cap='2411'),
            LevelChart(level='15', experience_cap='2746'),
            LevelChart(level='16', experience_cap='3115'),
            LevelChart(level='17', experience_cap='3523'),
            LevelChart(level='18', experience_cap='3973'),
            LevelChart(level='19', experience_cap='4470'),
            LevelChart(level='20', experience_cap='5018'),
            LevelChart(level='21', experience_cap='5624'),
            LevelChart(level='22', experience_cap='6291'),
            LevelChart(level='23', experience_cap='7028'),
            LevelChart(level='24', experience_cap='7842'),
            LevelChart(level='25', experience_cap='8740'),
            LevelChart(level='26', experience_cap='9730'),
            LevelChart(level='27', experience_cap='10824'),
            LevelChart(level='28', experience_cap='12031'),
            LevelChart(level='29', experience_cap='13363'),
            LevelChart(level='30', experience_cap='14833'),
            LevelChart(level='31', experience_cap='16456'),
            LevelChart(level='32', experience_cap='18247'),
            LevelChart(level='33', experience_cap='20224'),
            LevelChart(level='34', experience_cap='22406'),
            LevelChart(level='35', experience_cap='24815'),
            LevelChart(level='36', experience_cap='27473'),
            LevelChart(level='37', experience_cap='30308'),
            LevelChart(level='38', experience_cap='33348'),
            LevelChart(level='39', experience_cap='37224'),
            LevelChart(level='40', experience_cap='41171'),
            LevelChart(level='41', experience_cap='45529'),
            LevelChart(level='42', experience_cap='50339'),
            LevelChart(level='43', experience_cap='55649'),
            LevelChart(level='44', experience_cap='61512'),
            LevelChart(level='45', experience_cap='67983'),
            LevelChart(level='46', experience_cap='75127'),
            LevelChart(level='47', experience_cap='83014'),
            LevelChart(level='48', experience_cap='91721'),
            LevelChart(level='49', experience_cap='101333'),
            LevelChart(level='50', experience_cap='111945'),
            LevelChart(level='51', experience_cap='123660'),
            LevelChart(level='52', experience_cap='136594'),
            LevelChart(level='53', experience_cap='150872'),
            LevelChart(level='54', experience_cap='166636'),
            LevelChart(level='55', experience_cap='184040'),
            LevelChart(level='56', experience_cap='203254'),
            LevelChart(level='57', experience_cap='224466'),
            LevelChart(level='58', experience_cap='247886'),
            LevelChart(level='59', experience_cap='273742'),
            LevelChart(level='60', experience_cap='302288'),
            LevelChart(level='61', experience_cap='333804'),
            LevelChart(level='62', experience_cap='368599'),
            LevelChart(level='63', experience_cap='407015'),
            LevelChart(level='64', experience_cap='449428'),
            LevelChart(level='65', experience_cap='496254'),
            LevelChart(level='66', experience_cap='547953'),
            LevelChart(level='67', experience_cap='605032'),
            LevelChart(level='68', experience_cap='668051'),
            LevelChart(level='69', experience_cap='737627'),
            LevelChart(level='70', experience_cap='814445'),
            LevelChart(level='71', experience_cap='899257'),
            LevelChart(level='72', experience_cap='992895'),
            LevelChart(level='73', experience_cap='1096278'),
            LevelChart(level='74', experience_cap='1210421'),
            LevelChart(level='75', experience_cap='1336443'),
            LevelChart(level='76', experience_cap='1475581'),
            LevelChart(level='77', experience_cap='1629200'),
            LevelChart(level='78', experience_cap='1798808'),
            LevelChart(level='79', experience_cap='1986068'),
            LevelChart(level='80', experience_cap='2192818'),
            LevelChart(level='81', experience_cap='2421087'),
            LevelChart(level='82', experience_cap='2673114'),
            LevelChart(level='83', experience_cap='2941378'),
            LevelChart(level='84', experience_cap='3227854'),
            LevelChart(level='85', experience_cap='3534950'),
            LevelChart(level='86', experience_cap='3865477'),
            LevelChart(level='87', experience_cap='4222654'),
            LevelChart(level='88', experience_cap='4600040'),
            LevelChart(level='89', experience_cap='5002090'),
            LevelChart(level='90', experience_cap='5434153'),
            LevelChart(level='91', experience_cap='5891263'),
            LevelChart(level='92', experience_cap='6378991'),
            LevelChart(level='93', experience_cap='6903395'),
            LevelChart(level='94', experience_cap='7462274'),
            LevelChart(level='95', experience_cap='8052233'),
            LevelChart(level='96', experience_cap='8681351'),
            LevelChart(level='97', experience_cap='9357963'),
            LevelChart(level='98', experience_cap='10093707'),
            LevelChart(level='99', experience_cap='10962740'),
        ]
        db.session.add_all(levels_in_chart)
        db.session.commit()
        print('Seeding Cards...')
        mob_cards_to_commit = [
            Card(
                card_name="Goblin Scratch",
                gold_cost=100,
                mana_cost=2,
                mana_gain=0,
                hp_cost=0,
                damage=5,
                block=0,
                heal=0,
                description="Basic attack: Scratch for {damage} damage.",
            ),
            Card(
                card_name="Goblin Defend",
                gold_cost=80,
                mana_cost=1,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=3,
                heal=0,
                description="Defend and block {block} incoming damage.",
            ),
            Card(
                card_name="Scurry Strike",
                gold_cost=200,
                mana_cost=10,
                mana_gain=0,
                hp_cost=5,
                damage=10,
                block=0,
                heal=0,
                description="quickly strikes you \nfor {damage} damage.",
            ),
            Card(
                card_name="Tunnel Ambush",
                gold_cost=400,
                mana_cost=20,
                mana_gain=0,
                hp_cost=0,
                damage=10,
                block=10,
                heal=0,
                description="Prepares a ambush \ndeals {damage} damage \nblocking {block}",
            ),
            Card(
                card_name="Gnawing Distraction",
                gold_cost=250,
                mana_cost=15,
                mana_gain=0,
                hp_cost=0,
                damage=10,
                block=5,
                heal=0,
                description="Gnaws at you \nblocking {block} \ndealing {damage} damage",
            ),
            Card(
                card_name="Dirt Kick",
                gold_cost=425,
                mana_cost=30,
                mana_gain=0,
                hp_cost=0,
                damage=5,
                block=20,
                heal=0,
                description="Kicks up dirt \nblocking {block} \ndealing {damage} damage",
            ),
            Card(
                card_name="Mudslide Rush",
                gold_cost=800,
                mana_cost=45,
                mana_gain=0,
                hp_cost=0,
                damage=20,
                block=15,
                heal=0,
                description="Rushes and slides... \nblocking {block} \ndealing {damage} damage",
            ),
            Card(
                card_name="Sticky Grasp",
                gold_cost=800,
                mana_cost=45,
                mana_gain=0,
                hp_cost=0,
                damage=25,
                block=10,
                heal=0,
                description="Covers you in slime... \nblocking for {block} \nwhile dealing {damage} damage",
            ),
            Card(
                card_name="Mud Bath",
                gold_cost=800,
                mana_cost=35,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=0,
                heal=35,
                description="Natural Healing... \nRegains {heal} hitpoints",
            ),
            Card(
                card_name="Spore Burst",
                gold_cost=1000,
                mana_cost=50,
                mana_gain=0,
                hp_cost=50,
                damage=35,
                block=10,
                heal=10,
                description="cloud of spores\n dealing {damage} \nRegaining {heal} hitpoints \nBlocking {block}",
            ),
            Card(
                card_name="Mycelium Shield",
                gold_cost=1200,
                mana_cost=45,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=45,
                heal=0,
                description="A Mushroom shield... \nBlocking {block}",
            ),
            Card(
                card_name="Pollen Cloud",
                gold_cost=1500,
                mana_cost=55,
                mana_gain=0,
                hp_cost=5,
                damage=45,
                block=15,
                heal=15,
                description="A vile cloud \nBlocking {block} \nhealing{heal} \ndealing {damage}.",
            ),
            Card(
                card_name="Fungal Growth",
                gold_cost=3200,
                mana_cost=75,
                mana_gain=0,
                hp_cost=10,
                damage=0,
                block=0,
                heal=85,
                description="Regrows \nhealing {heal} hitpoints",
            ),
            Card(
                card_name="Prismatic Spray",
                gold_cost=2000,
                mana_cost=75,
                mana_gain=0,
                hp_cost=0,
                damage=50,
                block=50,
                heal=0,
                description="A fine mist \nhitting {damage} \nblocking {block}",
            ),
            Card(
                card_name="Dissolving Spit",
                gold_cost=1600,
                mana_cost=40,
                mana_gain=0,
                hp_cost=25,
                damage=80,
                block=0,
                heal=0,
                description="It Burns!! \nBurns {damage} damage",
            ),
            Card(
                card_name="Toxic Ooze",
                gold_cost=1800,
                mana_cost=40,
                mana_gain=0,
                hp_cost=25,
                damage=90,
                block=0,
                heal=0,
                description="Its RadioActive!?!? \n{damage} damage taken",
            )
        ]
        db.session.add_all(mob_cards_to_commit)
        cards_to_commit = [
            Card(
                card_name="Magic Bolt",
                image="/cards/Arcane2.png",
                gold_cost=200,
                mana_cost=5,
                mana_gain=0,
                hp_cost=0,
                damage=10,
                block=0,
                heal=0,
                description="Short and Simple \nFire a bolt that hits {damage} damage",
            ),
            Card(
                card_name="Magic Ward",
                image="/cards/Ward.png",
                gold_cost=200,
                mana_cost=5,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=10,
                heal=0,
                description="Short and Simple \nBlock {block} incoming damage",
            ),
            Card(
                card_name="Magic Band-aid",
                image="/cards/heal2.png",
                gold_cost=200,
                mana_cost=10,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=0,
                heal=10,
                description="Short and Simple \nRecover {heal} Hp",
            ),
            Card(
                card_name="Vitality Transfusion",
                image="/cards/Blood.png",
                gold_cost=400,
                mana_cost=0,
                mana_gain=20,
                hp_cost=10,
                damage=0,
                block=0,
                heal=0,
                description="Short and What? \nTrade {hp_cost} Hp\nFor {mana_gain} Mana",
            ),
            Card(
                card_name="Wack Em",
                image="/cards/Wack.png",
                gold_cost=100,
                mana_cost=0,
                mana_gain=0,
                hp_cost=0,
                damage=5,
                block=0,
                heal=0,
                description="Better Then Nothing...\nRight? \nWackEm {damage} Damage",
            ),
            Card(
                card_name="Hide Behind Somthing",
                image="/cards/Forest.png",
                gold_cost=100,
                mana_cost=0,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=5,
                heal=0,
                description="Better Then Nothing...\nRight? \nBlock {block} incoming damage",
            ),
            Card(
                card_name="Arcane Missile",
                image="/cards/Arcane.png",
                gold_cost=700,
                mana_cost=40,
                mana_gain=0,
                hp_cost=0,
                damage=40,
                block=0,
                heal=0,
                description="Missle of magic \ndealing {damage} Damage",
            ),
            Card(
                card_name="Frost Nova",
                image="/cards/Frost.png",
                gold_cost=1200,
                mana_cost=30,
                mana_gain=0,
                hp_cost=5,
                damage=30,
                block=20,
                heal=0,
                description="A Freezing Wave \ndealing {damage} Damage \nGain{block} Block",
            ),
            Card(
                card_name="Explosion",
                image="/cards/Explosion.png",
                gold_cost=1600,
                mana_cost=20,
                mana_gain=0,
                hp_cost=20,
                damage=80,
                block=0,
                heal=0,
                description="Explosion!?! \ndeal {damage} Damage \nHurting yourself for {hp_cost}",
            ),
            Card(
                card_name="Teleportation",
                image="/cards/Teleport.png",
                gold_cost=1200,
                mana_cost=25,
                mana_gain=0,
                hp_cost=5,
                damage=0,
                block=25,
                heal=0,
                description="Teleport \nGaining {block} Block",
            ),
            Card(
                card_name="Healing Aura",
                image="/cards/heal.png",
                gold_cost=1250,
                mana_cost=50,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=0,
                heal=25,
                description="Really a cleric's spell... \nRestore {heal} Hitpoints",
            ),
            Card(
                card_name="Barrier of Protection",
                image="/cards/Frost2.png",
                gold_cost=2000,
                mana_cost=50,
                mana_gain=0,
                hp_cost=0,
                damage=0,
                block=25,
                heal=25,
                description=" a protective barrier\nAlso heals {heal}? \nBlock {block} incoming damage",
            ),
            Card(
                card_name="Earthquake",
                image="/cards/Earthquake.png",
                gold_cost=900,
                mana_cost=25,
                mana_gain=0,
                hp_cost=15,
                damage=45,
                block=10,
                heal=0,
                description="Cracking the earth\ndealing {damage} Damage \nBlock {block} incoming damage",
            ),
            Card(
                card_name="Time Stop",
                image="/cards/Time.png",
                gold_cost=2500,
                mana_cost=70,
                mana_gain=100,
                hp_cost=0,
                damage=0,
                block=15,
                heal=5,
                description="Stop time to regain mana...\nRegain {mana_gain} Mana \nRegain {heal}} hitpoints \nBlocks {block} incoming damage",
            )
        ]
        
        db.session.add_all(cards_to_commit)
        db.session.commit()
        print('Seeding Mobs...')
        mobs_to_commit = [
            {
                "mob_name": "Tumbletwig",
                "image": "/mob/Tumbletwig.png",
                "level": "1",
                "hitpoints": "25",
                "max_hitpoints": "25",
                "mana": "25",
                "max_mana": "25",
                "draw": "2",
                "block": "0",
                "mob_decks": [
                    {"card_name": "Goblin Scratch"},
                    {"card_name": "Goblin Scratch"},
                    {"card_name": "Goblin Scratch"},
                    {"card_name": "Goblin Scratch"},
                    {"card_name": "Goblin Scratch"},
                    {"card_name": "Goblin Scratch"},
                    {"card_name": "Goblin Scratch"},
                    {"card_name": "Goblin Defend"},
                    {"card_name": "Goblin Defend"},
                    {"card_name": "Goblin Defend"},
                ],
            },
            {
                "mob_name": "Ratspawn",
                "image": "/mob/Ratspawn.png",
                "level": "2",
                "hitpoints": "38",
                "max_hitpoints": "38",
                "mana": "38",
                "max_mana": "38",
                "draw": "1",
                "block": "0",
                "mob_decks": [
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Scurry Strike"},
                    {"card_name": "Tunnel Ambush"},
                    {"card_name": "Tunnel Ambush"},
                    {"card_name": "Gnawing Distraction"},
                    {"card_name": "Gnawing Distraction"},
                    {"card_name": "Gnawing Distraction"},
                    {"card_name": "Gnawing Distraction"},
                    {"card_name": "Gnawing Distraction"},
                    {"card_name": "Gnawing Distraction"},
                    {"card_name": "Dirt Kick"},
                    {"card_name": "Dirt Kick"},
                    {"card_name": "Dirt Kick"},
                ],
            },
            {
                "mob_name": "Muckcrawler",
                "image": "/mob/Muckcrawler.png",
                "level": "3",
                "hitpoints": "57",
                "max_hitpoints": "57",
                "mana": "57",
                "max_mana": "57",
                "draw": "1",
                "block": "0",
                "mob_decks": [
                    {"card_name": "Mudslide Rush"},
                    {"card_name": "Mudslide Rush"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Mud Bath"},
                    {"card_name": "Mud Bath"},
                ],
            },
            {
                "mob_name": "Sporeling",
                "image": "/mob/Sporeling.png",
                "level": "4",
                "hitpoints": "86",
                "max_hitpoints": "86",
                "mana": "86",
                "max_mana": "86",
                "draw": "1",
                "block": "0",
                "mob_decks": [
                    {"card_name": "Spore Burst"},
                    {"card_name": "Spore Burst"},
                    {"card_name": "Spore Burst"},
                    {"card_name": "Mycelium Shield"},
                    {"card_name": "Mycelium Shield"},
                    {"card_name": "Pollen Cloud"},
                    {"card_name": "Pollen Cloud"},
                    {"card_name": "Fungal Growth"},
                ],
            },
            {
                "mob_name": "Slime glimmer",
                "image": "/mob/SlimeGlimmer.png",
                "level": "5",
                "hitpoints": "129",
                "max_hitpoints": "129",
                "mana": "129",
                "max_mana": "129",
                "draw": "2",
                "block": "0",
                "mob_decks": [
                    {"card_name": "Mudslide Rush"},
                    {"card_name": "Mudslide Rush"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Sticky Grasp"},
                    {"card_name": "Mud Bath"},
                    {"card_name": "Mud Bath"},
                    {"card_name": "Mud Bath"},
                    {"card_name": "Prismatic Spray"},
                    {"card_name": "Prismatic Spray"},
                    {"card_name": "Dissolving Spit"},
                    {"card_name": "Toxic Ooze"},
                ],
            }
            # {
            #     "mob_name": "Snakeshadow",
            #     "level": "6",
            #     "hitpoints": "194",
            #     "max_hitpoints": "194",
            #     "mana": "194",
            #     "max_mana": "194",
            #     "draw": "2",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Wispwhelp",
            #     "level": "7",
            #     "hitpoints": "291",
            #     "max_hitpoints": "291",
            #     "mana": "291",
            #     "max_mana": "291",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Gloomrat",
            #     "level": "8",
            #     "hitpoints": "437",
            #     "max_hitpoints": "437",
            #     "mana": "437",
            #     "max_mana": "437",
            #     "draw": "2",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Scurry Strike"},
            #         {"card_name": "Tunnel Ambush"},
            #         {"card_name": "Gnawing Distraction"},
            #         {"card_name": "Dirt Kick"},
            #     ],
            # },
            # {
            #     "mob_name": "Venomstalker",
            #     "level": "9",
            #     "hitpoints": "656",
            #     "max_hitpoints": "656",
            #     "mana": "656",
            #     "max_mana": "656",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Ironscale Drake",
            #     "level": "10",
            #     "hitpoints": "984",
            #     "max_hitpoints": "984",
            #     "mana": "984",
            #     "max_mana": "984",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Cursed Banshee",
            #     "level": "11",
            #     "hitpoints": "1476",
            #     "max_hitpoints": "1476",
            #     "mana": "1476",
            #     "max_mana": "1476",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Rotting Ghoul",
            #     "level": "12",
            #     "hitpoints": "2214",
            #     "max_hitpoints": "2214",
            #     "mana": "2214",
            #     "max_mana": "2214",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Embergeist",
            #     "level": "13",
            #     "hitpoints": "3321",
            #     "max_hitpoints": "3321",
            #     "mana": "3321",
            #     "max_mana": "3321",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Thunderhoof",
            #     "level": "14",
            #     "hitpoints": "4981",
            #     "max_hitpoints": "4981",
            #     "mana": "4981",
            #     "max_mana": "4981",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # },
            # {
            #     "mob_name": "Obsidian Serpent",
            #     "level": "15",
            #     "hitpoints": "7472",
            #     "max_hitpoints": "7472",
            #     "mana": "7472",
            #     "max_mana": "7472",
            #     "draw": "1",
            #     "block": "0",
            #     "mob_decks": [
            #         {"card_name": "Goblin Scratch"},
            #     ],
            # }
        ]

        for mob_info in mobs_to_commit:
            mob_decks_info = mob_info.pop("mob_decks", [])
            mob = Mob(**mob_info)
            db.session.add(mob)
            db.session.commit()

            for deck_info in mob_decks_info:
                card_name = deck_info["card_name"]
                card = Card.query.filter_by(card_name=card_name).first()

                if card:
                    deck = MobDeck(mob_id=mob.id, card_id=card.id)
                    db.session.add(deck)

        db.session.commit()