"""init2

Revision ID: e7bf2d28f93e
Revises: 96909855015d
Create Date: 2023-12-18 19:07:57.281672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bf2d28f93e'
down_revision = '96909855015d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience_cap', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience_cap', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skill_point', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('skill_point')
        batch_op.drop_column('experience_cap')
        batch_op.drop_column('experience')
        batch_op.drop_column('level')

    op.drop_table('level_chart')
    # ### end Alembic commands ###
